hash-format = "sha256"

[[files]]
file = "config/isxander-main-menu-credits.json"

[[files]]
file = "config/modpack_defaults/config/betterf3.json"

[[files]]
file = "config/modpack_defaults/config/bettergrass.json"

[[files]]
file = "config/modpack_defaults/config/cape-provider/config.json"

[[files]]
file = "config/modpack_defaults/config/chatpatches.json"

[[files]]
file = "config/modpack_defaults/config/citresewn.json"

[[files]]
file = "config/modpack_defaults/config/collective.json5"

[[files]]
file = "config/modpack_defaults/config/controlify.json"

[[files]]
file = "config/modpack_defaults/config/craftpresence.json"

[[files]]
file = "config/modpack_defaults/config/crash_assistant/config.toml"

[[files]]
file = "config/modpack_defaults/config/detailarmorbar.json"

[[files]]
file = "config/modpack_defaults/config/dynamic_fps.json"

[[files]]
file = "config/modpack_defaults/config/fastquit.toml"

[[files]]
file = "config/modpack_defaults/config/ferritecore.mixin.properties"

[[files]]
file = "config/modpack_defaults/config/iris.properties"

[[files]]
file = "config/modpack_defaults/config/isxander-main-menu-credits.json"

[[files]]
file = "config/modpack_defaults/config/lambdynlights.toml"

[[files]]
file = "config/modpack_defaults/config/locator-heads.json"

[[files]]
file = "config/modpack_defaults/config/modernfix-mixins.properties"

[[files]]
file = "config/modpack_defaults/config/modmenu.json"

[[files]]
file = "config/modpack_defaults/config/particlerain.json"

[[files]]
file = "config/modpack_defaults/config/puzzle.json"

[[files]]
file = "config/modpack_defaults/config/replaymod.json"

[[files]]
file = "config/modpack_defaults/config/resourcepackchecker/resourcepackchecker.properties"

[[files]]
file = "config/modpack_defaults/config/sound_physics_remastered/occlusion.properties"

[[files]]
file = "config/modpack_defaults/config/sound_physics_remastered/reflectivity.properties"

[[files]]
file = "config/modpack_defaults/config/sound_physics_remastered/sound_rates.properties"

[[files]]
file = "config/modpack_defaults/config/sound_physics_remastered/soundphysics.properties"

[[files]]
file = "config/modpack_defaults/config/subtle_effects/blocks.toml"

[[files]]
file = "config/modpack_defaults/config/subtle_effects/entities.toml"

[[files]]
file = "config/modpack_defaults/config/subtle_effects/environment.toml"

[[files]]
file = "config/modpack_defaults/config/subtle_effects/general.toml"

[[files]]
file = "config/modpack_defaults/config/subtle_effects/items.toml"

[[files]]
file = "config/modpack_defaults/config/vmp.properties"

[[files]]
file = "config/modpack_defaults/config/voxy-config.json"

[[files]]
file = "config/modpack_defaults/config/world-host.json5"

[[files]]
file = "config/modpack_defaults/config/zfastnoise.mixin.properties"

[[files]]
file = "config/modpack_defaults/options.txt"

[[files]]
file = "mods/3dskinlayers.pw.toml"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/armor-3d.pw.toml"
metafile = true

[[files]]
file = "mods/better-block-entities.pw.toml"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
metafile = true

[[files]]
file = "mods/bettergrassify.pw.toml"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/calcmod.pw.toml"
metafile = true

[[files]]
file = "mods/cape-provider.pw.toml"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
metafile = true

[[files]]
file = "mods/chatanimation.pw.toml"
metafile = true

[[files]]
file = "mods/chatpatches.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/configmanager.pw.toml"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
metafile = true

[[files]]
file = "mods/craftpresence.pw.toml"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
metafile = true

[[files]]
file = "mods/cull-fewer-leaves.pw.toml"
metafile = true

[[files]]
file = "mods/detail-armor-bar-reconstructed.pw.toml"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
metafile = true

[[files]]
file = "mods/e4mc.pw.toml"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
metafile = true

[[files]]
file = "mods/esf.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/fix-keyboard-on-linux.pw.toml"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
metafile = true

[[files]]
file = "mods/ixeris.pw.toml"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
metafile = true

[[files]]
file = "mods/lightoverlay.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/locator-heads.pw.toml"
metafile = true

[[files]]
file = "mods/macos-input-fixes.pw.toml"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
metafile = true

[[files]]
file = "mods/modernfix-mvus.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/modmenuc.pw.toml"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/nemos-inventory-sorting.pw.toml"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
metafile = true

[[files]]
file = "mods/overlaylib.pw.toml"
metafile = true

[[files]]
file = "mods/paginatedadvancements.pw.toml"
metafile = true

[[files]]
file = "mods/particle-core.pw.toml"
metafile = true

[[files]]
file = "mods/particle-effects.pw.toml"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
metafile = true

[[files]]
file = "mods/renderscale.pw.toml"
metafile = true

[[files]]
file = "mods/replaymod.pw.toml"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
metafile = true

[[files]]
file = "mods/scribble.pw.toml"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
metafile = true

[[files]]
file = "mods/server-resource-pack-checker.pw.toml"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
metafile = true

[[files]]
file = "mods/skyboxify.pw.toml"
metafile = true

[[files]]
file = "mods/smm-lib.pw.toml"
metafile = true

[[files]]
file = "mods/smooth-scroll.pw.toml"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
metafile = true

[[files]]
file = "mods/subtle-effects.pw.toml"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
metafile = true

[[files]]
file = "mods/unilib.pw.toml"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/voxy.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
metafile = true

[[files]]
file = "mods/zfastnoise.pw.toml"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/chat-reporting-helper.pw.toml"
metafile = true
