name = "LEMON³"
author = "SkywardMC, OffsetMonkey538, Isaiah"
version = "1.43.0+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f90675580f783d13b3a277410cd2a2b40bf23d8df9e4d58fdeb629fa63a62efc"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
no-internal-hashes = true
