name = "LEMON³"
author = "SkywardMC, OffsetMonkey538, Isaiah"
version = "1.43.0+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
no-internal-hashes = true
