name = "LEMON³"
author = "SkywardMC, OffsetMonkey538, Isaiah"
version = "1.43.0+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "989d0ebd895916e7d16742442b279e51b6b7a5e5134ef8edb8d07779d9a04a3e"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
no-internal-hashes = true
