name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-read-only: false
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.5'
      - name: Install Packwiz
        run: go install github.com/packwiz/packwiz@latest
      - name: Build
        run: |
          rm -rf build
          mkdir -p build
          cd prismSource
          zip -r ../build/LEMONCUBE.zip *
          cd ../versions/fabric/1.21.11
          cp -r config mods resourcepacks index.toml pack.toml ../../../build
          cd ../../../mod
          ./gradlew build
          cd ../build
          cp ../mod/build/libs/*.jar mods/
          rm mods/*-sources.jar
          packwiz refresh --build
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v4
        id: deployment
        with:
          path: build
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
